name: Hectus-Block-Battles
version: '${version}'
main: net.hectus.hectusblockbattles.HectusBlockBattles
api-version: 1.19
authors: [ MarcPG ]
description: Plugin for the Block Battles game mode on the Hectus Network
website: https://hectus.net/blockbattles
commands:
  match:
    description: Puts two players in a Block Battles™ match.
    usage: /match <player> <player>
  structure:
    description: Manages the structures of the Block Battles™ game mode. Currently only saves structures.
    usage: /structure x1 y1 z1 x2 y2 z2 <name>
  giveup:
    description: Let you lose the match.
    usage: /giveup
  test:
    description: Test command
    usage: /test